### ISSUE TITLE
Available To Play Somewhere?

### ISSUE THREAD

**Issue by DavidXochipilli** [Raymondd/Halma#1]
Hi @Raymondd,
thanks for your awesome Halma game!
Did you publish it into the [Windows Store](https://www.microsoft.com/en-us/store/apps), [Google Play](https://play.google.com/store) or is it playable on a [website](https://azure.microsoft.com/en-us/)?

**Comment by razfriman** [comment]
No, but this includes source code to run the game itself

**Comment by DavidXochipilli** [comment]
Can you add setup informations (and maybe screenshots) in the README please? I am a newbie and do not know how to run the game myself. 😅
